import type { AgentToolDefinition } from "../toolTypes";

export const taskTools: AgentToolDefinition[] = [
  {
    id: "tasks.list",
    name: "List tasks",
    description: "Inspect current task metadata for workspace reasoning.",
    domain: "tasks",
    capability: "inspect",
    mode: "read",
    riskLevel: "none",
    requiresApproval: false,
    approvalScope: "view_only",
    reversible: true,
    externalEffect: false,
    inputSchema: [],
    outputSchema: {
      type: "array",
      description: "Task metadata including titles, completion state, and dates.",
      containsSensitiveData: false,
    },
    enabled: true,
    version: "1.0.0",
    tags: ["workspace", "tasks", "read"],
    examples: [
      {
        title: "Inspect open tasks",
        input: {},
        expectedOutcome: "Returns task metadata for display or reasoning.",
      },
    ],
    constraints: ["Read-only contract.", "Does not create, update, complete, or delete tasks."],
  },
  {
    id: "tasks.create",
    name: "Create task",
    description: "Future contract for creating a task after explicit approval.",
    domain: "tasks",
    capability: "create",
    mode: "write",
    riskLevel: "medium",
    requiresApproval: true,
    approvalScope: "single_step",
    reversible: true,
    externalEffect: true,
    inputSchema: [
      {
        name: "title",
        type: "string",
        required: true,
        description: "Task title.",
      },
      {
        name: "dueDate",
        type: "date",
        required: false,
        description: "Optional due date.",
      },
    ],
    outputSchema: {
      type: "object",
      description: "Created task metadata.",
      fields: [],
    },
    enabled: true,
    version: "1.0.0",
    tags: ["future", "tasks", "write"],
    examples: [
      {
        title: "Create a task",
        input: { title: "Review invoices" },
        expectedOutcome: "Creates a task only after explicit approval in a future executor.",
      },
    ],
    constraints: ["Contract only.", "No handler is registered.", "Requires explicit user approval."],
  },
  {
    id: "tasks.update",
    name: "Update task",
    description: "Future contract for updating task metadata after explicit approval.",
    domain: "tasks",
    capability: "update",
    mode: "write",
    riskLevel: "medium",
    requiresApproval: true,
    approvalScope: "single_step",
    reversible: true,
    externalEffect: true,
    inputSchema: [
      {
        name: "taskId",
        type: "string",
        required: true,
        description: "Task identifier.",
      },
      {
        name: "fields",
        type: "object",
        required: true,
        description: "Task fields to update.",
      },
    ],
    outputSchema: {
      type: "object",
      description: "Updated task metadata.",
      fields: [],
    },
    enabled: true,
    version: "1.0.0",
    tags: ["future", "tasks", "write"],
    examples: [
      {
        title: "Update due date",
        input: { taskId: "task-1", fields: { dueDate: "2026-07-12" } },
        expectedOutcome: "Updates the task only after explicit approval in a future executor.",
      },
    ],
    constraints: ["Contract only.", "No handler is registered.", "Requires explicit user approval."],
  },
  {
    id: "tasks.complete",
    name: "Complete task",
    description: "Future contract for marking a task complete after explicit approval.",
    domain: "tasks",
    capability: "complete",
    mode: "write",
    riskLevel: "medium",
    requiresApproval: true,
    approvalScope: "single_step",
    reversible: true,
    externalEffect: true,
    inputSchema: [
      {
        name: "taskId",
        type: "string",
        required: true,
        description: "Task identifier.",
      },
    ],
    outputSchema: {
      type: "object",
      description: "Completed task metadata.",
      fields: [],
    },
    enabled: true,
    version: "1.0.0",
    tags: ["future", "tasks", "write"],
    examples: [
      {
        title: "Complete a task",
        input: { taskId: "task-1" },
        expectedOutcome: "Completes the task only after explicit approval in a future executor.",
      },
    ],
    constraints: ["Contract only.", "No handler is registered.", "Requires explicit user approval."],
  },
];
