import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

interface ReportData {
  month: string;
  totalIncome: number;
  totalExpenses: number;
  balance: number;
  byCategory: { category: string; amount: number }[];
  transactions: { date: string; type: string; category: string; amount: number; notes: string | null }[];
}

export async function generateMonthlyReport(data: ReportData): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const page = pdfDoc.addPage([595, 842]); // A4
  const { width, height } = page.getSize();
  let y = height - 50;

  const drawText = (
    text: string, x: number, yPos: number,
    size = 10, bold = false,
    color = rgb(0.1, 0.1, 0.1),
  ) => {
    page.drawText(text, { x, y: yPos, size, font: bold ? boldFont : font, color });
  };

  const drawLine = (yPos: number) => {
    page.drawLine({
      start: { x: 40, y: yPos }, end: { x: width - 40, y: yPos },
      thickness: 0.5, color: rgb(0.8, 0.8, 0.8),
    });
  };

  // Header band
  page.drawRectangle({ x: 0, y: height - 80, width, height: 80, color: rgb(0.06, 0.71, 0.81) });
  drawText('Monthly Financial Report', 40, height - 35, 18, true, rgb(1, 1, 1));
  drawText(data.month, 40, height - 58, 12, false, rgb(0.9, 0.9, 0.9));
  y = height - 110;

  // Summary cards
  drawText('SUMMARY', 40, y, 8, true, rgb(0.5, 0.5, 0.5));
  y -= 20;

  const cards = [
    { label: 'Total Income', value: `€${data.totalIncome.toFixed(2)}`, color: rgb(0.06, 0.73, 0.51) },
    { label: 'Total Expenses', value: `€${data.totalExpenses.toFixed(2)}`, color: rgb(0.94, 0.27, 0.27) },
    { label: 'Balance', value: `€${data.balance.toFixed(2)}`, color: data.balance >= 0 ? rgb(0.06, 0.73, 0.51) : rgb(0.94, 0.27, 0.27) },
  ];

  cards.forEach((card, i) => {
    const x = 40 + i * 170;
    page.drawRectangle({ x, y: y - 45, width: 155, height: 50, color: rgb(0.97, 0.97, 0.97), borderColor: rgb(0.88, 0.88, 0.88), borderWidth: 0.5 });
    drawText(card.label, x + 10, y - 15, 8, false, rgb(0.5, 0.5, 0.5));
    drawText(card.value, x + 10, y - 35, 13, true, card.color);
  });

  y -= 70;
  drawLine(y);
  y -= 20;

  // Category breakdown
  drawText('EXPENSES BY CATEGORY', 40, y, 8, true, rgb(0.5, 0.5, 0.5));
  y -= 15;

  data.byCategory.slice(0, 10).forEach(cat => {
    drawText(cat.category, 40, y, 10);
    drawText(`€${cat.amount.toFixed(2)}`, width - 100, y, 10, true);
    y -= 18;
  });

  y -= 10;
  drawLine(y);
  y -= 20;

  // Transactions
  drawText('TRANSACTIONS', 40, y, 8, true, rgb(0.5, 0.5, 0.5));
  y -= 15;

  // Table header
  page.drawRectangle({ x: 40, y: y - 15, width: width - 80, height: 18, color: rgb(0.93, 0.93, 0.93) });
  drawText('Date', 45, y - 10, 8, true);
  drawText('Description', 110, y - 10, 8, true);
  drawText('Category', 340, y - 10, 8, true);
  drawText('Amount', width - 105, y - 10, 8, true);
  y -= 20;

  data.transactions.slice(0, 30).forEach((tx, i) => {
    if (y < 60) return;
    if (i % 2 === 0) {
      page.drawRectangle({ x: 40, y: y - 12, width: width - 80, height: 16, color: rgb(0.98, 0.98, 0.98) });
    }
    drawText(tx.date, 45, y - 8, 8);
    drawText((tx.notes ?? tx.category).slice(0, 35), 110, y - 8, 8);
    drawText(tx.category, 340, y - 8, 8);
    const amtColor = tx.type === 'income' ? rgb(0.06, 0.73, 0.51) : rgb(0.94, 0.27, 0.27);
    drawText(`${tx.type === 'income' ? '+' : '-'}€${Number(tx.amount).toFixed(2)}`, width - 105, y - 8, 8, false, amtColor);
    y -= 16;
  });

  page.drawText(`Generated by dailyFlow · ${new Date().toLocaleDateString()}`, {
    x: 40, y: 30, size: 8, font, color: rgb(0.6, 0.6, 0.6),
  });

  return pdfDoc.save();
}
