-- Add AI fields to documents table
ALTER TABLE public.documents
  ADD COLUMN IF NOT EXISTS summary TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS summary_language TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS summary_generated_at TIMESTAMPTZ DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS extracted_text TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS word_count INTEGER DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS key_points TEXT[] DEFAULT '{}';
